### PR TITLE
improve test coverage of JodaTimeRangeRandomizers

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
By the way there seems to be something wrong with the travis build, because it is successful despite a test failure in the log:

>Failed tests: 
>
>EnhancedRandomImplTest.annotatedRandomizerArgumentsShouldBeCorrectlyParsed:420 
>
>Expecting:
><2016-01-30T23:51:23.220>
>to be in period:
>[2016-01-10T00:00:00.000, 2016-01-30T00:00:00.000[
>
>Tests run: 315, Failures: 1, Errors: 0, Skipped: 1

**Comment by benas** [comment]
Got this error locally today and thought it was fixed..

https://github.com/benas/random-beans/commit/2d171c934057f6782e946bf6a28e548996492950

https://github.com/benas/random-beans/commit/3105f36301f74acb99e827c6a64637e1ed61ac96

But it looks like it is failing randomly. The build is not stable

**Comment by benas** [comment]
Not sure I understand, looks like ObjectMapper from jackson is not accurate:

```java
ObjectMapper objectMapper = new ObjectMapper();
Date date = objectMapper.convertValue("2016-01-30T23:59:59", Date.class);
System.out.println("date = " + date); // prints: date = Sun Jan 31 00:59:59 CET 2016
```

The input value is conform to the [default date format](https://github.com/FasterXML/jackson-databind/blob/bb8a0b35d7b1e1e7b9b77c6525dca16429f3f1bb/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java), but the converted date is wrong .. Hope I'm not missing somehting

**Comment by benas** [comment]
It seems there are some [issues](https://github.com/FasterXML/jackson-databind/issues?utf8=%E2%9C%93&q=is%3Aissue%20iso8601%20) with default format ( see this [comment](https://github.com/FasterXML/jackson-databind/blob/bb8a0b35d7b1e1e7b9b77c6525dca16429f3f1bb/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java#L23))

I don't have time to investigate more on this, I've [added](e50f5f9569255315d1d64f19e375ea0620b948e1) a date format that will be documented. The ObjectMapper is working fine when I specify a date format.

**Pull request merged**
