### PR TITLE
Provide BOM artefact with correct parent poms

### LINKED ISSUE #249: Provide BOM artefact
As Random-Beans has 5 modules it would be great if you could provide a BOM artefact as e.g. Jackson also does.
This Bill of Material contains consistent version information for all random-beans modules.

It would look like this:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>io.github.benas</groupId>
	<artifactId>random-beans-bom</artifactId>
	<version>3.6.0</version>
	<packaging>pom</packaging>

	<name>Random Beans BOM</name>
	<url>https://github.com/benas/random-beans</url>

	<scm>
		<url>git@github.com:benas/random-beans.git</url>
		<connection>scm:git:git@github.com:benas/random-beans.git</connection>
		<developerConnection>scm:git:git@github.com:benas/random-beans.git</developerConnection>
		<tag>random-beans-parent-3.6.0</tag>
	</scm>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>http://opensource.org/licenses/mit-license.php</url>
		</license>
	</licenses>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans-randomizers</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans-validation</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans-jodatime</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans-spring</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
```

Now it is possible to use this in someones dependencyManagement section:
```xml
			<dependency>
				<groupId>io.github.benas</groupId>
				<artifactId>random-beans-bom</artifactId>
				<version>${version.random-beans}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```

Sorry for not providing a pull request, I have company proxy issues.

Kind regards,
Michael

### PR DESCRIPTION
**Pull request by reitzmichnicht**
I splitted parent pom into project and parent pom to separate the dependencyManagement section.
This is the common way to introduce a BOM.

Fixes #249

### CODE REVIEW

**Comment by reitzmichnicht** [comment]
Sorry I'm a github newbie, it was planned to have 2 separate pull requests for it

**Comment by benas** [comment]
Hi,

Thank you for these updates!

I think the issue with the current bom as I implemented it is that is should not be part of the project (ie, don't have `random-beans-parent` as parent [here](https://github.com/benas/random-beans/blob/master/random-beans-bom/pom.xml#L7-L11)). Jackson for instance is using a [different repo](https://github.com/FasterXML/jackson-bom) for the bom.

I think if I remove the `random-beans-parent` parent from the current bom (and replace it with the one from sonatype, just to be able to release the artifact to maven central) it should work. Can I test this before merging your changes?

Kind regards,
Mahmoud

**Comment by reitzmichnicht** [comment]
Even Jackson has a wrong bom :) , they define junit version in the bom.
For example weld has done it right. With my approach which is the same as weld you are still able to define the same maven plugin versions for all your modules and for the bom.

**Comment by benas** [comment]
> Even Jackson has a wrong bom :) , they define junit version in the bom.

ok, I will not take them as a reference. I was just curious to see how others do.

**Comment by benas** [comment]
After further digging into this, there is no issue if the bom has a parent section. Spring Boot's BOM [has a parent](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml#L6-L11) section and is working fine.

I just retested the current bom I introduced earlier and it is working fine. I created a new project with the following pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test-rb-bom</groupId>
    <artifactId>test-rb-bom</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>io.github.benas</groupId>
            <artifactId>random-beans-spring</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.benas</groupId>
                <artifactId>random-beans-bom</artifactId>
                <version>3.8.0-SNAPSHOT</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
```

Both `random-beans-spring` and `random-beans` artifacts are imported with the correct version.

@reitzmichnicht Can you confirm?

**Comment by benas** [comment]
As mentioned previously, please open a separate PR for `Ipv4AddressRandomizer` and `MacAddressRandomizer`. 

I'm closing this PR as explained in #249.

**Comment by benas** [comment]
> Do you plan a major release in the next time?

v3.8 has been released last week. Next is v3.9 and the release date is not set yet, but one of my resolutions in 2019 is to release early, release often.. (Ask me by the end of <strike>January</strike> February 🙃)

>I will create some PRs in the next days/weeks.

You can update/reopen this PR by keeping only `Ipv4AddressRandomizer` and `MacAddressRandomizer` and it will be ready to merge. May be add an `Ipv6AddressRandomizer` too? I see that faker already provides `faker.internet().ipV6Address()`.

**Pull request closed without merging**
