### PR TITLE
replace constant default seed by random seed to make the generated va…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…lues random again (#113)

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
If this is merged I think we should expose a method for the user to determine the seed used by `EnhancedRandom`.

**Comment by benas** [comment]
Good idea indeed, that's more random..

**Comment by punkratz312** [comment]
Nice approach, fixed the problem: (First 2.0.0, Second 3.0.0-SNAPSHOT)
screen shot 2016-04-15 at 11 15 01
screen shot 2016-04-15 at 11 18 50

**Comment by benas** [comment]
> Good idea indeed, that's more random..

The build is also random :smile: It's failing now ..

**Comment by punkratz312** [comment]
WorX on my machine (dad34b18b70a34ab54533fd9bf76f653a26e65a9) mvn clean install 8 times always success

**Comment by benas** [comment]
likewise here. But I succeeded to make it fail after 20 attempts..

the build was green on the PR: https://travis-ci.org/benas/random-beans/builds/123129961
but fails after the merge: https://travis-ci.org/benas/random-beans/builds/123257530

a bit weird, I'll check that

**Pull request merged**
