### PR TITLE
fix StringRandomizer never returns Strings of maxStringLength

### PR DESCRIPTION
**Pull request by kermit-the-frog**
same failure as in #220

### CODE REVIEW

**Comment by kermit-the-frog** [comment]
Sorry, I haven't run the tests.

**Comment by kermit-the-frog** [comment]
@benas Could you please explain the failed tests to me? As far as I understand they just make sure, that `StringRandomizer.getRandomValue` always returns the same value with specific `minLength, maxLength, seed`. But now I've changed the implementation of `StringRandomizer.getRandomValue` and the result for specific `minLength, maxLength, seed` has changed. Is it ok to change the `expectedValue` of these tests?

**Comment by benas** [comment]
Thank you for reporting this issue and for your PR!

> Is it ok to change the expectedValue of these tests?

Yes, this is way to go.

**Comment by benas** [comment]
Great! Thank you for the quick update.

Let's merge that.

**Pull request merged**
