### PR TITLE
partial migration to junit 5 and junit-dataprovider 2

### PR DESCRIPTION
**Pull request by PascalSchumacher**
The test using mockito are still junit 4 because there is no junit 5 mockito extension yet (see: https://github.com/mockito/mockito/issues/445, https://github.com/mockito/mockito/pull/1221)

### CODE REVIEW

**Comment by benas** [comment]
Oh great! thanks for the effort.

I was planning to do it for v4 but you did it before 😄

**Comment by reitzmichnicht** [comment]
You can use Parametrized Tests with MethodSource instead of junit-dataprovider

**Comment by PascalSchumacher** [comment]
@benas I think this is ready to merge, as the junit-dataprovider 2 release is available. We can migrate the mockito tests when the mockito junit 5 extension has been released. Do you agree?

**Comment by benas** [comment]
Hello,

Sorry for the late reply. I don't like the new github setting of not showing *all* notifications in my timeline.. I don't care if someone starred or forked a repo. The most important notifications (issue opened, PR submitted, etc) are not shown and hidden in the notifications tab (and looks like this in not configurable). Anyway, please forgive me if I reply late than expected 😄 

Good job for moving to Junit 5!!
And no worries for mockito junit 5 extension, we can add it afterwards.

Best regards,
Mahmoud

**Comment by PascalSchumacher** [comment]
No problem.

I enabled github e-mail notifications ages ago, so I get emails for issues and pull requests opened for repositories I watch.

Cheers,
Pascal

**Pull request merged**
