### PR TITLE
issue #234 - RandomizerProxy should now be able to accept Supplier as lambda.

### PR DESCRIPTION
**Pull request by LucasAndersson**

### CODE REVIEW

**Comment by benas** [comment]
Hi Lucas,

This is great. Thank you very much for your time and effort!

I'll merge your PR asap. Just a quick note, I think it is not necessary to make RandmomizerProxy public. I've just tested and both your test (in this PR) and the test [here](https://github.com/benas/random-beans/issues/234#issuecomment-279228003) still pass. Do you agree?

Kind regards
Mahmoud

**Comment by LucasAndersson** [comment]
Hi Mahmoud

RandomizerProxyTest has to be in a separate package from RandomizerProxy, therefore RandomizerProxy can't be package private. Otherwise the tests will falsely pass even without my fix.

Br
Lucas

**Comment by benas** [comment]
Lucas, sorry for the confusion, I was not clear enough in my previous comment.
Let's forget about RandomizerProxy visibility and take random beans as a black box for a moment.

If I understand correctly your bug reporting, random beans is unable to generate an instance of a given type when a custom supplier is passed as a lambda expression.
The test mentioned by @PascalSchumacher (which is an integration test) fails which version 3.5.0 .

If I take only the following modification ( + the unit test but not RandmomizerProxy visibility change) from your PR:

```diff
     @Override
      public Object invoke(final Object proxy, final Method method, final Object[] args) throws Throwable {
          if ("getRandomValue".equals(method.getName())) {
-            return target.getClass().getMethod("get").invoke(target, args);
+            Method getMethod = target.getClass().getMethod("get");
+            getMethod.setAccessible(true);
+            return getMethod.invoke(target, args);
          }
          return null;
      }
```

the test pass, which is for me enough to consider the bug as fixed. Do you see? This is what I meant by it is not necessary to make RandmomizerProxy public.

Now the question of making RandomizerProxy public or package private is another discussion (if you want, I can explain in details the decision of why it is package private)
Whether to put test classes in the same package as tested classes or not is yet another discussion.

The unit test you added in your PR is correct for me. What we can do is adding an integration test in a separate package to make sure everything is working as expected. What do you think?

**Comment by LucasAndersson** [comment]
I understand your comment now, I was initially thinking to do that but I figured I would implement the test as close to the problem as possible. I just hoped that the visibility of RandomizerProxy wasn't important. Updated my PR according to your comments.

**Comment by benas** [comment]
Thank you for the update 👍 
You could have kept the unit test, it was fine. I'll add it.

Let's merge this fix for now.

Many thanks!

**Pull request merged**
