### PR TITLE
upgrade to fast-classpath-scanner 1.9.19

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by benas** [comment]
Thanks for the update. I was about to release v3.1 last weekend but I've got a bunch of issues with maven release plugin. When I do `mvn release:prepare` everything is fine, then, when I run `mvn release:perform` it fails with a super weird exception :rage1: It was a [PITA](https://github.com/benas/random-beans/commit/960219f7a177fa3fbc480b26894a2d37c11fa0d6) just like last month with release v3.0:

image

Anyway, I need to fix that asap. Will <del>try</del> **do** this weekend :muscle:

**Comment by PascalSchumacher** [comment]
Tough luck. :( saw some of the commits by change last weekend. I remember reading some post blasting the release plugin a few years back, but I do not have much experience with it myself.

Good luck with the release. :) Fingers crossed. :+1:

**Comment by PascalSchumacher** [comment]
Congrats on the release. :+1: 

Did you find the cause of the problem?

**Comment by benas** [comment]
After a hair pulling session, here is the winner: b6a30346ee736288c83462e92ecef3371bfeb34c 😄 

The problem is tricky. The release plugin first builds and generates javadoc for the core module (version 3.1.0). Then, for next modules, the aggregate goal tries to look for the core module version 3.1.0 in maven central, which is not released yet! Hence, it fails .. And of course, all of this is running just fine in the prepare phase.

Anyway, I removed the javadoc plugin from the build. I'll invoke it manually when needed.

**Comment by benas** [comment]
2 days ago, a new version of the maven javadoc plugin [has been released](https://mail-archives.apache.org/mod_mbox/maven-announce/201606.mbox/%3Cop.yiuy6lohkdkhrr%40desktop-2khsk44%3E) fixing a special bug : https://issues.apache.org/jira/browse/MJAVADOC-437

The bug that cost me some strands of hair.. I want my hair back!

**Comment by PascalSchumacher** [comment]
Looks like you were not the only one, there are three duplicates of this bug. The oldest one from 2007. :(

**Pull request merged**
