### PR TITLE
v2 enum randomization

### PR DESCRIPTION
**Pull request by korniltsev**
The problem: Generated enums of the same type are not random.
The problem is in the `io.github.benas.randombeans.EnhancedRandomImpl#randomize` . It creates              a new EnumRandomizer for every call

### CODE REVIEW

**Comment by korniltsev** [comment]
Btw I have red tests not related to the patch.
```
Tests in error:
  CityRandomizerTest.setUp:36 » LocaleDoesNotExist ru_RU could not be found, doe...
  CompanyRandomizerTest.setUp:36 » LocaleDoesNotExist ru_RU could not be found, ...
  CountryRandomizerTest.setUp:36 » LocaleDoesNotExist ru_RU could not be found, ...
  CreditCardNumberRandomizerTest.setUp:36 » LocaleDoesNotExist ru_RU could not b...
```

**Comment by PascalSchumacher** [comment]
@korniltsev Thanks for the pull request.

The test failures are probably caused by a bug in an old versions of java-faker. Or do you also get them when using the latest master of  random-beans?

**Comment by korniltsev** [comment]
@PascalSchumacher master is green

**Comment by benas** [comment]
Hi @korniltsev 

Thank you for your PR.

Which version of random beans are you using?

**Comment by korniltsev** [comment]
I use version 2.0.0. I try to make it work on android. Please see my comments on https://github.com/benas/random-beans/issues/62

**Comment by benas** [comment]
Hi @korniltsev 

Have you tried to use the latest version 3.4?
This bug has been already fixed (see 3ae95025a03c933c62811ba5f9fdef89e9363636).

Kind regards
Mahmoud

**Comment by korniltsev** [comment]
Yes, I've tried. I would love to use it, but AFAIK there is no way to run master branch on android because of java version 1.8 and stream api. It is sad, but Android is now limited (and will be limited for long time) to java 1.7. If I find myself in need of features from 3.x version I'l probably make a fork, decrease java version, replace stream api usages with something else (may be RxJava). But for now I'l stick to the v2.x.

**Comment by benas** [comment]
Oh yes I understand. That caused me a lot of hair pulling sessions as you may have seen and commented on issue #62.

The problem is I'm really lacking time to maintain and release multiple versions of RB at the same time.
Please use your fork if you need version 2.x

I'm really sorry about that, Hope you understand my situation.

Kind regards
Mahmoud

**Pull request closed without merging**
