### PR TITLE
replace org.reflections with io.github.lukehutch.fast-classpath-scanner

### PR DESCRIPTION
**Pull request by PascalSchumacher**
fast-classpath-scanner has no dependencies and seems to be better maintained

### CODE REVIEW

**Comment by benas** [comment]
I was aware of Reflections library, but not fast-classpath-scanner. Looks interesting!

But with hindsight, do we really need a whole dependency for just 10 lines of code? Can we try to do it without this library and see if it really worth it?

I do believe there is a trade-off here and I try to make a pragmatic decision. If we really struggle with classpath scanning for concrete sub-types, then let's definitely go for using fast-classpath-scanner.

**Comment by PascalSchumacher** [comment]
I haven't actually checked how much code is needed from Reflections/Fast-Classpath-Scanner. If it's really just a few lines I'm all for removing the dependency.

**Comment by benas** [comment]
> If it's really just a few lines I'm all for removing the dependency.

Great! We are on the same page of the same philosophy

**Comment by PascalSchumacher** [comment]
Related to this: I think it is also be possible to remove the commons-lang3 dependency, because random-beans uses just three of its methods.

**Comment by PascalSchumacher** [comment]
I took a look at the implementation of fast-classpath-scanner.

We can not replace the dependency by just copying a few lines of code. Extracting the parts we need looks like a lot of work.

I do not think this is worth the effort for an optional dependency. 

Fast-classpath-scanner has no dependencies so it only adds a single 100k jar to the classpath of users that like to use random-beans with classpath scanning.

**Comment by benas** [comment]
> We can not replace the dependency by just copying a few lines of code

This is not what I meant, sorry if I was not clear. The goal is not to extract the code as is from the library and remove the dependency. That would be a shame.

Looking at the changes, here is the only "feature" we are using from fast-classpath-scanner (correct me if I'm wrong):

```
 List<String> subTypes = type.isInterface() ? classpathScanner.getNamesOfClassesImplementing(type) : classpathScanner.getNamesOfSubclassesOf(type);
```

I thought about trying to write those 2 methods with vanilla java by ourselves (may be in a different way or even simpler than FCS) and not relying on a third party library. If we really struggle with it and found it takes so much effort, then adding the library makes sense.

That said, since you already took a look at the code of FCS and found it's not that easy, that's fine for me, I trust you. Now, after this little trade-off analysis, Let's make our life easier by using this library :smile:

> Fast-classpath-scanner has no dependencies so it only adds a single 100k jar

The size does not matter (I mean.. in this context :stuck_out_tongue_winking_eye:) if the library is worth it. and it does in our case. Thank you for suggesting FCS.

**Comment by PascalSchumacher** [comment]
Sorry, it wasn't you that did not make himself clear but me. :(

What I meant by
>We can not replace the dependency by just copying a few lines of code

was: I think we can not copy or write a simplified version of the parts of fast-classpath-scanner that random-beans requires without significant effort (as far as I can tell, I'm not an expert at class-path-scanning :)).

Besides the two methods you mention we also require `classpathScanner.scan();`.

**Comment by benas** [comment]
Ok that's fine don't worry.

I'm not expert neither, classpath scanning is tricky and it would be risky to deal with it for an optional dependency. Let's delegate that to FCS. I do believe we made a pragmatic decision after all :smile:

**Pull request merged**
