### PR TITLE
prototype for mokito like api #29

### PR DESCRIPTION
**Pull request by PascalSchumacher**
I hacked together a quick and very unfinished prototype.

Naming is obviously completely wrong.

### CODE REVIEW

**Comment by benas** [comment]
Thank you for this PR. Happy to see byte buddy here :-)

Please give me some time to take a look at your changes and how this technique works behind the scene.

**Comment by PascalSchumacher** [comment]
Sure. No need to hurry. :)

Also please feel free to reject. I'm not sure this feature is worth the effort it will require.

**Comment by PascalSchumacher** [comment]
The more I think about it the less I'm convinced that this feature is worth the considerable implementation effort it requires.

**Comment by benas** [comment]
I do agree. I think the added value of the syntactic sugar is not worth it in comparison with the effort needed to implement it. Although it is a good idea, I think we can discard it for now. I'm closing this PR along with the original feature request ( #29 )

**Pull request closed without merging**
