### PR TITLE
do not try to populate collections with nested parametrized types (fixes #208)

### LINKED ISSUE #208: ClassCastException on wildcard generics in collections
Hello, Trying to figure out the best way around this. I want to populate some JAX-B beans. They have fields like this:

`@XmlElementRef(name = "reportedLocation", namespace = "http://api.foo.com/v3", type = JAXBElement.class)
    protected List<JAXBElement<? extends ReportedLocation>> reportedLocations;`

I get a ClassCastException exception from this:

`Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at io.github.benas.randombeans.CollectionPopulator.getRandomCollection(CollectionPopulator.java:68)
    at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:93)
    at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:79)
    at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:162)
    at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:153)
    at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:124)
    ... 203 more`

There are quite a few of these. I have a custom registry for some other abstract classes I have but I'm unsure of the best way around this one.

Another suggestion, it might be nice if the EnhancedRandom were to have a brute force mode where it never ever stops for these kinds of errors and just skips them (and logs an error maybe) 

Great library everyone!

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
I'm not sure this is the correct way to fix this, so please do not merge yet. I need some more time to think about it.

**Comment by PascalSchumacher** [comment]
@benas What do you think? Is there a better/cleaner way to fix this? Thanks!

**Comment by benas** [comment]
Hi,

Sorry for the late reply, I was off for a few days.

That looks fine. Thanks for the fix!

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
No problem. Thanks for the feedback. :)

**Pull request merged**
