### PR TITLE
#184 Reuse EnumRandomizer instances in EnhancedRandomImpl to ensure randomness.

### PR DESCRIPTION
**Pull request by rodriguealcazar**
Fix for #184.

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Thank you for this PR. I've tried that same fix a few days ago (which I reverted because it was pushed by error):

https://github.com/benas/random-beans/commit/44909563c91946d47573036a89948799b7e2bfb8

But this does not really fix the problem. When a type has a field of type enum, the same instance should be always generated for the same seed. Hence, using a new seed every time an `EnumRandomizer` is returned makes some tests to fail. We need to find a solution for this case.

Kind regards
Mahmoud

**Comment by rodriguealcazar** [comment]
I see, I should have obviously tried to run all test and understand the impact better.

> When a type has a field of type enum, the same instance should be always generated for the same seed

Is this just because some tests rely on this behaviour or is it by design?

**Comment by benas** [comment]
No problem, don't worry.

This is by design and more general to enums. Given a type, the same instance should be generated for the same seed. This is the purpose of the seed. Here is the test case: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java#L266

**Comment by rodriguealcazar** [comment]
I've added a map in `EnhancedRandomImpl` that keeps an instance of `EnumRandomizer` per enum type. That fixes the problem of always restarting the randomness with the same seed - root cause of this ticket - and keeps the "same seed gives same enum instance" property.

**Comment by benas** [comment]
Fantastic! Thank you for this fix.

Kind regards
Mahmoud

**Pull request merged**
