### PR TITLE
Backreferences

### PR DESCRIPTION
**Pull request by marmer**
Dear Populators,

I'm currently working on a project with a lot of model classes with backreferences. So I decided to add some support for at least simple backreferences. Because the project is based on Java6 (and not yet upgradeable to Java7) I made the changes based on your 1.2.0 release instead of your already upgraded version 1.3.0-SNAPSHOT. I hope you guys like the contribution :)

### CODE REVIEW

**Comment by benas** [comment]
Hi,

Thank you for this addition!

FYI, the minimum version of Java was reverted to 1.6 (see 508c42951b803665fea2f46a6ad772e8d3b373f9) in the master branch. Could you please update your PR? Note that there are some important changes due to renaming the project to Random Beans.

In regards to "backreferences", can you provide an example of what this PR is intended to add?
Many thanks upfront
Regards
Mahmoud

**Comment by benas** [comment]
Hello @marmer and happy new year !

Any update on this issue? It would be great if I can include it in the next release.

Kind regards
Mahmoud

**Comment by marmer** [comment]
Hello benas. Happy new year for you too.

No, I had no time yet. But I hope i can merge it on sunday. When is the next release sceduled?

**Comment by benas** [comment]
Hello,

No problem don't worry! I love open source because we have no stupid constraints like time and budget :smile: So take your time and let me know when your are done.

I planned to release 2.0 by the end of this month but this is a soft deadline :smile:

Anyway, in the mean while, could you please give an example of what this PR is intended to fix/add?
Is the term "back reference" related to issue #44 ?

Thank you

**Comment by marmer** [comment]
Well, not sure whether it works with a backreference to the same entity type (I'll test it tomorrow, but I don't think so). But it works like charm when the parent and child relationship is based on two different types (at least 1:1, 1:n, n:1 relationships but maybe not n:m). We already use the modified version of 1.2 with it for our projects in my company:)

n:m relationships and relations to the same type may be a bit harder to create.

**Comment by marmer** [comment]
So, after to many tries to merge my changes I surrender. It seems that it was a bad idea of mine to add changes based on 1.2.0. The structural changes are to big since then.

I'll later try to recreate theese changes based on a more recent commit but this must wait a little more. Sorry.

**Pull request closed without merging**
